title: La Raíz 🌿
description: La Raíz es una organización universitaria que se dedica a la formación y acción en  sustentabilidad. Nace el año 2020 como continuación del trabajo que venía  desarrollando CVerde en la UC desde el año 2014. Nos dedicamos a la acción a  través del desarrollo de proyectos y emprendimientos ligados a distintas áreas socioambientales tales como la política, el compostaje, la educación ambiental, huertas agroecológicas, reciclaje, artivismo y voluntariados. Con ellos buscamos concientizar a la comunidad universitaria sobre las distintas problemáticas atingentes a la crisis climática y qué se puede hacer desde nuestras posiciones como estudiantes para combatirlas.  
theme: jekyll-theme-cayman

# Opciones adicionales para el diseño
show_downloads: false
google_analytics:
